// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TienThoBookStore.Infrastructure.Contexts;

#nullable disable

namespace TienThoBookStore.Infrastructure.Migrations
{
    [DbContext(typeof(TienThoBookStoreDbContext))]
    [Migration("20250427170055_AddEmailConfirmationSentAt")]
    partial class AddEmailConfirmationSentAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("EmailConfirmationSentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("emailConfirmationSentAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("author");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ContentFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contentFull");

                    b.Property<string>("ContentSample")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contentSample");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("coverImage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("publishedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "Tô Hoài",
                            CategoryId = 1,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover1.jpg",
                            Description = "\r\n        “Dế Mèn Phiêu Lưu Ký” là hành trình kỳ thú của chú Dế Mèn dũng cảm, ham khám phá\r\n        và không ngừng vươn lên giữa bao thử thách. Từ những ngày an toàn trong hang ổ,\r\n        Dế Mèn lạc vào thế giới rộng lớn đầy phức tạp: gặp gỡ bạn bè như Dế Trũi,\r\n        trải qua giông bão thiên nhiên, đối mặt kẻ thù hung hãn và học được bài học\r\n        “lá lành đùm lá rách”. Tác phẩm kết hợp sự hóm hỉnh, ngôn từ giản dị nhưng\r\n        giàu tính nhân văn, giúp độc giả mọi lứa tuổi cảm nhận tình bạn, lòng quả\r\n        cảm và thái độ nhân ái giữa cuộc sống muôn màu.",
                            Price = 120000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dế Mèn Phiêu Lưu Ký"
                        },
                        new
                        {
                            BookId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Author = "Nam Cao",
                            CategoryId = 1,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover2.jpg",
                            Description = "\r\n        “Chí Phèo” là tác phẩm kinh điển khắc họa bi kịch xã hội đương thời qua hình\r\n        ảnh người nông dân bị xã hội cuốn vào vòng vây mất nhân dạng. Chí, từ một kẻ\r\n        chất phác, lương thiện, dần bị đẩy vào con đường tội lỗi sau bao bất công,\r\n        từng nếm trải sự đay nghiến, lênh đênh giữa say sưa và tuyệt vọng. Khi gặp\r\n        Thị Nở, Chí khát khao một giây phút bình yên, trở về kiếp người lương thiện.\r\n        Tác phẩm đặt ra câu hỏi về quyền sống, lòng thương xót và trách nhiệm của xã\r\n        hội đối với những mảnh đời bất hạnh.",
                            Price = 150000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chí Phèo"
                        },
                        new
                        {
                            BookId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Author = "Nam Cao",
                            CategoryId = 1,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover3.jpg",
                            Description = "\r\n        Câu chuyện “Lão Hạc” kể về người nông dân nghèo khổ, tảo tần nuôi con giữa\r\n        những cánh đồng gió lộng. Lão Hạc yêu thương cậu Vàng như con đẻ, nhưng chịu\r\n        áp lực cơm áo, ông buộc lòng bán đi vật nuôi duy nhất. Nỗi đau mất mát chất\r\n        chồng, cuộc sống càng khốn khó hơn khi xã hội không còn chỗ cho lòng hi sinh\r\n        trọn tình. Tác phẩm là bức tranh hiện thực đau đớn, lay động lòng người, phơi\r\n        bày bi kịch gia đình và thân phận con người trước thử thách khắc nghiệt.",
                            Price = 130000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lão Hạc"
                        },
                        new
                        {
                            BookId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Author = "Ngô Tất Tố",
                            CategoryId = 1,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover4.jpg",
                            Description = "\r\n        “Tắt Đèn” khai thác đề tài nông dân Việt Nam dưới ánh sáng luật pháp thực\r\n        dân – phong kiến. Nhân vật chị Dậu cùng chồng con vật lộn với cảnh đói rét,\r\n        hà khắc của chủ điền, luật thuế chồng chất. Từ hình ảnh người vợ gồng mình\r\n        bảo vệ con khỏi cảnh bị phạt chó đến khoảnh khắc thắt cổ tự vẫn, tác giả\r\n        vẽ nên bức tranh xã hội tàn nhẫn và khát khao bứt phá khỏi kiếp nô lệ.\r\n        Tác phẩm thôi thúc suy ngẫm về công lý, lương tri và giá trị của sinh mạng con người.",
                            Price = 110000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tắt Đèn"
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Author = "Charles Darwin",
                            CategoryId = 2,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover5.jpg",
                            Description = "\r\n        “On the Origin of Species” (Nguồn gốc các loài) là công trình trọng đại mở ra\r\n        lý thuyết tiến hóa qua chọn lọc tự nhiên, giải thích cơ chế sinh học đưa muôn\r\n        loài đến sự đa dạng hiện nay. Darwin phân tích di truyền, chuyển đổi hình thái,\r\n        môi trường sống và sự cạnh tranh sinh tồn. Tác phẩm không chỉ thay đổi cách ta\r\n        nhìn về nguồn gốc con người mà còn đặt nền móng cho sinh học hiện đại, kích\r\n        thích tranh luận khoa học và triết học suốt nhiều thập kỷ.",
                            Price = 200000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "On the Origin of Species"
                        },
                        new
                        {
                            BookId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Author = "Ernst Mach",
                            CategoryId = 2,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover6.jpg",
                            Description = "\r\n        Trong “The Science of Mechanics”, Ernst Mach trình bày quan điểm xây dựng\r\n        cơ học dựa trên quan sát thực nghiệm và cảm giác chủ quan. Ông chỉ ra rằng\r\n        khái niệm lực, chuyển động nên được hiểu như biểu hiện của trải nghiệm\r\n        người quan sát. Tác phẩm kết hợp vật lý lý thuyết và triết học khoa học,\r\n        thách thức cách tiếp cận Newton truyền thống, đồng thời mở đường cho sự\r\n        phát triển của tâm lý học nhận thức và thuyết tương đối sau này.",
                            Price = 180000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Science of Mechanics"
                        },
                        new
                        {
                            BookId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Author = "Adam Smith",
                            CategoryId = 3,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover7.jpg",
                            Description = "\r\n        “The Wealth of Nations” là nền tảng của kinh tế học cổ điển,\r\n        nơi Adam Smith phân tích cách thị trường tự do, phân công lao động và lợi ích\r\n        cá nhân dẫn đến thịnh vượng chung. Ông đề xuất “bàn tay vô hình” điều tiết\r\n        giá cả và sản xuất, kêu gọi hạn chế can thiệp chính phủ. Tác phẩm ảnh hưởng\r\n        sâu rộng đến chính sách kinh tế, tư tưởng tự do và học thuyết kinh tế hiện\r\n        đại, trở thành công cụ nghiên cứu không thể thiếu.",
                            Price = 220000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wealth of Nations"
                        },
                        new
                        {
                            BookId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Author = "John Maynard Keynes",
                            CategoryId = 3,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover8.jpg",
                            Description = "\r\n        Được viết ngay sau Thế chiến I, “The Economic Consequences of the Peace” là\r\n        phân tích sắc bén của Keynes về hậu quả kinh tế từ Hiệp ước Versailles. Ông\r\n        cảnh báo các điều khoản bồi thường quá khắc nghiệt sẽ phá vỡ nền kinh tế\r\n        châu Âu, làm gia tăng bất ổn chính trị và khủng hoảng lạm phát. Tác phẩm là\r\n        lời kêu gọi thận trọng trong thiết kế hòa ước và chính sách tái cấu trúc\r\n        kinh tế hậu chiến, có tầm ảnh hưởng lâu dài đến chính sách quốc tế.",
                            Price = 210000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Economic Consequences of the Peace"
                        },
                        new
                        {
                            BookId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Author = "Lê Tắc",
                            CategoryId = 4,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover9.jpg",
                            Description = "\r\n        “An Nam Chí Lược” là biên niên sử do Lê Tắc biên soạn, ghi chép chi tiết\r\n        lịch sử Đại Việt từ thời Tiền Lê đến Nhà Trần, đồng thời phản ánh quan hệ chính\r\n        trị, văn hóa với Trung Quốc. Tác giả trình bày các sự kiện qua lăng kính\r\n        quan lại lưu vong, kết hợp tư liệu chữ Hán và phong tục địa phương, tạo nên\r\n        tư liệu quý giá cho nghiên cứu lịch sử và văn hoá Việt Nam thời trung đại.",
                            Price = 90000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "An Nam Chí Lược"
                        },
                        new
                        {
                            BookId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Author = "Trần Trọng Kim",
                            CategoryId = 4,
                            ContentFull = "",
                            ContentSample = "",
                            CoverImage = "cover10.jpg",
                            Description = "\r\n        “Việt Nam Sử Lược” của Trần Trọng Kim là tổng hợp toàn diện lịch sử Việt\r\n        Nam từ thuở sơ khai đến thời Nguyễn. Tác giả trình bày sự kiện rõ ràng,\r\n        mạch lạc, kết hợp sử liệu chính thống và truyền thuyết dân gian, tiếp cận\r\n        gần gũi với độc giả thời đại. Tác phẩm đặt nền móng cho nghiên cứu sử học\r\n        Việt Nam hiện đại, được tái bản nhiều lần và trở thành giáo trình cơ bản\r\n        cho sinh viên và người yêu sử.",
                            Price = 95000m,
                            PublishedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Việt Nam Sử Lược"
                        });
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookmarkId"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("pageNumber");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookmarkId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmark", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CartId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("CartItemId");

                    b.HasIndex("BookId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Tiểu thuyết"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Khoa học"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Kinh tế"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Lịch sử"
                        });
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Highlight", b =>
                {
                    b.Property<int>("HighlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HighlightId"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("ContentExcerpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contentExcerpt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("pageNumber");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HighlightId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Highlight", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noteText");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("pageNumber");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoteId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LastPage")
                        .HasColumnType("int")
                        .HasColumnName("lastPage");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastReadAt");

                    b.Property<float>("PercentCompleted")
                        .HasColumnType("real")
                        .HasColumnName("percentCompleted");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BookId");

                    b.ToTable("ReadingProgress", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("paymentDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalAmount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionDetailId"));

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unitPrice");

                    b.HasKey("TransactionDetailId");

                    b.HasIndex("BookId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionDetail", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Book", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("Bookmarks")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Cart", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("Carts")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("CartItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Highlight", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("Highlights")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("Highlights")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Note", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("Notes")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("Notes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.ReadingProgress", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Review", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("Reviews")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TienThoBookStore.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.TransactionDetail", b =>
                {
                    b.HasOne("TienThoBookStore.Domain.Entities.Book", "Book")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TienThoBookStore.Domain.Entities.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Carts");

                    b.Navigation("Highlights");

                    b.Navigation("Notes");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Book", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("CartItems");

                    b.Navigation("Highlights");

                    b.Navigation("Notes");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("Reviews");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("TienThoBookStore.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
